use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum CommandCode {
    AppStart = 0x01,
    SendMsg = 0x02,
    SendChanMsg = 0x03,
    GetContacts = 0x04,
    GetTime = 0x05,
    SetTime = 0x06,
    SendAdvert = 0x07,
    SetName = 0x08,
    UpdateContact = 0x09,
    GetMsg = 0x0A,
    SetRadio = 0x0B,
    SetTxPower = 0x0C,
    ResetPath = 0x0D,
    SetCoords = 0x0E,
    RemoveContact = 0x0F,
    ShareContact = 0x10,
    ExportContact = 0x11,
    ImportContact = 0x12,
    Reboot = 0x13,
    GetBattery = 0x14,
    SetTuning = 0x15,
    DeviceQuery = 0x16,
    ExportPrivateKey = 0x17,
    ImportPrivateKey = 0x18,
    SendLogin = 0x1A,
    SendStatusReq = 0x1B,
    SendLogout = 0x1D,
    GetChannel = 0x1F,
    SetChannel = 0x20,
    SignStart = 0x21,
    SignData = 0x22,
    SignFinish = 0x23,
    SendTrace = 0x24,
    SetDevicePin = 0x25,
    SetOtherParams = 0x26,
    GetTelemetry = 0x27,
    GetCustomVars = 0x28,
    SetCustomVar = 0x29,
    BinaryReq = 0x32,
    FactoryReset = 0x33,
    PathDiscovery = 0x34,
    SetFloodScope = 0x36,
    SendControlData = 0x37,
    GetStats = 0x38,
    RequestAdvert = 0x39,
}

impl CommandCode {
    pub fn from_byte(b: u8) -> Option<Self> {
        match b {
            0x01 => Some(Self::AppStart),
            0x02 => Some(Self::SendMsg),
            0x03 => Some(Self::SendChanMsg),
            0x04 => Some(Self::GetContacts),
            0x05 => Some(Self::GetTime),
            0x06 => Some(Self::SetTime),
            0x07 => Some(Self::SendAdvert),
            0x08 => Some(Self::SetName),
            0x09 => Some(Self::UpdateContact),
            0x0A => Some(Self::GetMsg),
            0x0B => Some(Self::SetRadio),
            0x0C => Some(Self::SetTxPower),
            0x0D => Some(Self::ResetPath),
            0x0E => Some(Self::SetCoords),
            0x0F => Some(Self::RemoveContact),
            0x10 => Some(Self::ShareContact),
            0x11 => Some(Self::ExportContact),
            0x12 => Some(Self::ImportContact),
            0x13 => Some(Self::Reboot),
            0x14 => Some(Self::GetBattery),
            0x15 => Some(Self::SetTuning),
            0x16 => Some(Self::DeviceQuery),
            0x17 => Some(Self::ExportPrivateKey),
            0x18 => Some(Self::ImportPrivateKey),
            0x1A => Some(Self::SendLogin),
            0x1B => Some(Self::SendStatusReq),
            0x1D => Some(Self::SendLogout),
            0x1F => Some(Self::GetChannel),
            0x20 => Some(Self::SetChannel),
            0x21 => Some(Self::SignStart),
            0x22 => Some(Self::SignData),
            0x23 => Some(Self::SignFinish),
            0x24 => Some(Self::SendTrace),
            0x25 => Some(Self::SetDevicePin),
            0x26 => Some(Self::SetOtherParams),
            0x27 => Some(Self::GetTelemetry),
            0x28 => Some(Self::GetCustomVars),
            0x29 => Some(Self::SetCustomVar),
            0x32 => Some(Self::BinaryReq),
            0x33 => Some(Self::FactoryReset),
            0x34 => Some(Self::PathDiscovery),
            0x36 => Some(Self::SetFloodScope),
            0x37 => Some(Self::SendControlData),
            0x38 => Some(Self::GetStats),
            0x39 => Some(Self::RequestAdvert),
            _ => None,
        }
    }
}

impl fmt::Display for CommandCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            Self::AppStart => "CMD_APPSTART",
            Self::SendMsg => "CMD_SEND_MSG",
            Self::SendChanMsg => "CMD_SEND_CHAN_MSG",
            Self::GetContacts => "CMD_GET_CONTACTS",
            Self::GetTime => "CMD_GET_TIME",
            Self::SetTime => "CMD_SET_TIME",
            Self::SendAdvert => "CMD_SEND_ADVERT",
            Self::SetName => "CMD_SET_NAME",
            Self::UpdateContact => "CMD_UPDATE_CONTACT",
            Self::GetMsg => "CMD_GET_MSG",
            Self::SetRadio => "CMD_SET_RADIO",
            Self::SetTxPower => "CMD_SET_TX_POWER",
            Self::ResetPath => "CMD_RESET_PATH",
            Self::SetCoords => "CMD_SET_COORDS",
            Self::RemoveContact => "CMD_REMOVE_CONTACT",
            Self::ShareContact => "CMD_SHARE_CONTACT",
            Self::ExportContact => "CMD_EXPORT_CONTACT",
            Self::ImportContact => "CMD_IMPORT_CONTACT",
            Self::Reboot => "CMD_REBOOT",
            Self::GetBattery => "CMD_GET_BATTERY",
            Self::SetTuning => "CMD_SET_TUNING",
            Self::DeviceQuery => "CMD_DEVICE_QUERY",
            Self::ExportPrivateKey => "CMD_EXPORT_PRIVATE_KEY",
            Self::ImportPrivateKey => "CMD_IMPORT_PRIVATE_KEY",
            Self::SendLogin => "CMD_SEND_LOGIN",
            Self::SendStatusReq => "CMD_SEND_STATUS_REQ",
            Self::SendLogout => "CMD_SEND_LOGOUT",
            Self::GetChannel => "CMD_GET_CHANNEL",
            Self::SetChannel => "CMD_SET_CHANNEL",
            Self::SignStart => "CMD_SIGN_START",
            Self::SignData => "CMD_SIGN_DATA",
            Self::SignFinish => "CMD_SIGN_FINISH",
            Self::SendTrace => "CMD_SEND_TRACE",
            Self::SetDevicePin => "CMD_SET_DEVICE_PIN",
            Self::SetOtherParams => "CMD_SET_OTHER_PARAMS",
            Self::GetTelemetry => "CMD_GET_TELEMETRY",
            Self::GetCustomVars => "CMD_GET_CUSTOM_VARS",
            Self::SetCustomVar => "CMD_SET_CUSTOM_VAR",
            Self::BinaryReq => "CMD_BINARY_REQ",
            Self::FactoryReset => "CMD_FACTORY_RESET",
            Self::PathDiscovery => "CMD_PATH_DISCOVERY",
            Self::SetFloodScope => "CMD_SET_FLOOD_SCOPE",
            Self::SendControlData => "CMD_SEND_CONTROL_DATA",
            Self::GetStats => "CMD_GET_STATS",
            Self::RequestAdvert => "CMD_REQUEST_ADVERT",
        };
        write!(f, "{name}")
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum ResponseCode {
    Ok = 0x00,
    Error = 0x01,
    ContactStart = 0x02,
    Contact = 0x03,
    ContactEnd = 0x04,
    SelfInfo = 0x05,
    MsgSent = 0x06,
    ContactMsgRecv = 0x07,
    ChannelMsgRecv = 0x08,
    CurrentTime = 0x09,
    NoMoreMsgs = 0x0A,
    ContactUri = 0x0B,
    Battery = 0x0C,
    DeviceInfo = 0x0D,
    ChannelInfo = 0x12,
    CustomVars = 0x15,
    Stats = 0x18,
    Advertisement = 0x80,
    PathUpdate = 0x81,
    Ack = 0x82,
    MessagesWaiting = 0x83,
    LoginSuccess = 0x85,
    LoginFailed = 0x86,
    StatusResponse = 0x87,
    NewAdvert = 0x8A,
    TelemetryResponse = 0x8B,
    BinaryResponse = 0x8C,
}

impl ResponseCode {
    pub fn from_byte(b: u8) -> Option<Self> {
        match b {
            0x00 => Some(Self::Ok),
            0x01 => Some(Self::Error),
            0x02 => Some(Self::ContactStart),
            0x03 => Some(Self::Contact),
            0x04 => Some(Self::ContactEnd),
            0x05 => Some(Self::SelfInfo),
            0x06 => Some(Self::MsgSent),
            0x07 => Some(Self::ContactMsgRecv),
            0x08 => Some(Self::ChannelMsgRecv),
            0x09 => Some(Self::CurrentTime),
            0x0A => Some(Self::NoMoreMsgs),
            0x0B => Some(Self::ContactUri),
            0x0C => Some(Self::Battery),
            0x0D => Some(Self::DeviceInfo),
            0x12 => Some(Self::ChannelInfo),
            0x15 => Some(Self::CustomVars),
            0x18 => Some(Self::Stats),
            0x80 => Some(Self::Advertisement),
            0x81 => Some(Self::PathUpdate),
            0x82 => Some(Self::Ack),
            0x83 => Some(Self::MessagesWaiting),
            0x85 => Some(Self::LoginSuccess),
            0x86 => Some(Self::LoginFailed),
            0x87 => Some(Self::StatusResponse),
            0x8A => Some(Self::NewAdvert),
            0x8B => Some(Self::TelemetryResponse),
            0x8C => Some(Self::BinaryResponse),
            _ => None,
        }
    }
}

impl fmt::Display for ResponseCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            Self::Ok => "OK",
            Self::Error => "ERROR",
            Self::ContactStart => "CONTACT_START",
            Self::Contact => "CONTACT",
            Self::ContactEnd => "CONTACT_END",
            Self::SelfInfo => "SELF_INFO",
            Self::MsgSent => "MSG_SENT",
            Self::ContactMsgRecv => "CONTACT_MSG_RECV",
            Self::ChannelMsgRecv => "CHANNEL_MSG_RECV",
            Self::CurrentTime => "CURRENT_TIME",
            Self::NoMoreMsgs => "NO_MORE_MSGS",
            Self::ContactUri => "CONTACT_URI",
            Self::Battery => "BATTERY",
            Self::DeviceInfo => "DEVICE_INFO",
            Self::ChannelInfo => "CHANNEL_INFO",
            Self::CustomVars => "CUSTOM_VARS",
            Self::Stats => "STATS",
            Self::Advertisement => "ADVERTISEMENT",
            Self::PathUpdate => "PATH_UPDATE",
            Self::Ack => "ACK",
            Self::MessagesWaiting => "MESSAGES_WAITING",
            Self::LoginSuccess => "LOGIN_SUCCESS",
            Self::LoginFailed => "LOGIN_FAILED",
            Self::StatusResponse => "STATUS_RESPONSE",
            Self::NewAdvert => "NEW_ADVERT",
            Self::TelemetryResponse => "TELEMETRY_RESPONSE",
            Self::BinaryResponse => "BINARY_RESPONSE",
        };
        write!(f, "{name}")
    }
}
